### PR TITLE
Upgrade to net.6.0

### PR DESCRIPTION
**Pull request by ffquintella**

### CODE REVIEW

**Comment by jeroenhabets** [comment]
@jkmu do you have any plans to support .Net 6.0 by merging this PR, or alternatively support netstandard 2.1 or 2.0? Cheers!

**Comment by ffquintella** [comment]
Yes I am supporting .net7.0 now.

**Comment by jeroenhabets** [comment]
@ffquintella perhaps better to clearly state you're maintaining a fork (I realize you tried a PR for long enough)

FWIW due to lack of activity/maintenance we no longer consider this library an option. Nevertheless all the best to you both.

**Comment by ffquintella** [comment]
yes I am maintaining a fork ... even created a new nuget package since I got no answer from my PR

**Pull request closed without merging**
